export const EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE";
export const EMPLOYEE_ADD = "EMPLOYEE_ADD";
export const EMPLOYEES_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";
export const EMPLOYEE_SAVE_EDIT = "EMPLOYEE_SAVE_EDIT";
export const EMPLOYEE_FIRE = 'EMPLOYEE_FIRE';
export const YES_FIRE = 'YES_FIRE';
export const NO_FIRE = 'NO_FIRE';
